# Generated by Django 3.0.5 on 2021-12-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('classification', models.CharField(max_length=30)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('start', models.CharField(blank=True, max_length=25)),
                ('end', models.CharField(blank=True, max_length=25)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'suggestions',
            },
        ),
    ]
